### ISSUE TITLE
Ability to revert unsaved changes

### ISSUE THREAD

**Issue by terrysahaidak** [isprojects/mstform#101]
I was looking through the docs and didn't find a way to revert changes to the model.

I have a profile settings screen, which has some base editable info of a user and a "save" button.
Sometimes user can decide to dismiss editing. But any changes to the model are already in my model.

How can I decline changes or make a change to the real node just after the save have happened?

**Comment by faassen** [comment]
Thanks for your question!

mstform doesn't have direct support for this (at the moment, we could potentially add support). It's rather fundamental to its architecture that the node is kept in sync with the form itself. But you can make it work by keeping a MST snapshot of your node of the state before the form was shown, and then if the user presses cancel, apply that snapshot again.

We could add support for this - make such a snapshot when form state is made, and apply it automatically to the node if the user calls a 'revert' method on the state.

**Comment by terrysahaidak** [comment]
Hi @faassen, thanks for your reply. I've realized that the easiest way to reach it will be something like:

```js
const m = M.create();

const initialState = getSnapshot(m);

function save(node) {
  applySnapshot(m, getSnapshot(node));
}

const form = form.state(clone(m), {
  backend: {  
    save,
  }
};

function reset() {
  applySnapshot(form.node, initialState);
}
```
