### ISSUE TITLE
access / get state or node in validators

### ISSUE THREAD

**Issue by rajesh-coalesce** [isprojects/mstform#114]
Hi,

Currently from docs it looks like validators functions get field and its value.
It will be good to have state from mst or node (similar which we get in onChange) so as to perform validations against other values.
Scenario is - some field's value should be "correct" if checkbox is checked or age is <30 etc. or else the value must be "wrong"...

Hope there's already a way to achieve this by accessing other field's values from state during specific field validation.

Thanks!

**Comment by faassen** [comment]
Hey, sorry for being late getting back to you.

There are three answers:

* validators *can* receive a context as a second argument, which you can define yourself.

* with the getError hook. this is open-ended - you get the accessor of the field (or other accessor) and you can use it (including the state, and the underlying node) to return any type of error message.

* the backend processing infrastructure. This doesn't actually *have* to hook up to a backend. This receives the MST instance the form is displaying and the path of the field being modified. It needs to return a structure that describes error messages for particular fields: 

```
    errorValidations: [
        { id: "one", messages: [{ path: "/b", message: "This is wrong" }] }
    ],
```

I hope that helps! If you have a good idea on how to expand this, I'm very curious to hear more!

**Comment by rajesh-coalesce** [comment]
Hi, 
Thanks for reply and I was out of action on this for some time.
The options you explained does help especially the backend processing. However, I have another issue to validate onBlur and not as user types.
Will close this and create another ticket for the same.

Thanks!
