### ISSUE TITLE
[SSR] Seems to brake when used from the server

### ISSUE THREAD

**Issue by fullofcaffeine** [isprojects/mstform#116]
Hi!

I'm trying to introduce `mstform` in an isomorphic js app, and after installing it and trying to reproduce the demo included in the source-code, I'm getting the following error from `webpack`:

```
yarn dev-server                                               [2.5.0]
yarn run v1.12.3
$ cross-env NODE_ENV=development node scripts/start-ssr server
[2019-11-07T23:40:56.641Z] [server] Compiling 
Time: 2577ms
Built at: 11/07/2019 5:40:59 PM
Entrypoint server = server.css server.js server.css.map server.js.map
Debugger listening on ws://127.0.0.1:9229/cee52786-d951-4851-9b0d-22840166de63
For help, see: https://nodejs.org/en/docs/inspector

/home/fullofcaffeine/workspace/code/app/node_modules/mstform/dist/webpack:/mstform/webpack/universalModuleDefinition:10
})(window, function(__WEBPACK_EXTERNAL_MODULE__0__, __WEBPACK_EXTERNAL_MODULE__1__) {
 ^
ReferenceError: window is not defined
    at Object.window (/home/fullofcaffeine/workspace/code/app/node_modules/mstform/dist/webpack:/mstform/webpack/universalModuleDefinition:10:2)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.mstform (/home/fullofcaffeine/workspace/code/app/build/server/webpack:/external "mstform":1:1)
    at __webpack_require__ (/home/fullofcaffeine/workspace/code/app/build/server/webpack:/webpack/bootstrap:19:1)
^CProcess ended
```

It's not like I'll use it from the server, but it should be able to run the same code on the server so that React can pick it up on the client. 

Does anyone know why is it trying to pass the `window` object there? Is this module not ready for SSR/isomorphic apps?

Thanks in advance!

**Comment by faassen** [comment]
We have done absolutely nothing to support SSR, but that said there is little in it that should prevent it given that mstform focuses on validation. It's possible there are some defaults in there that use window as a fallback. I welcome an analysis of the source and a PR for this.

**Comment by fullofcaffeine** [comment]
Hi @faassen, thanks for the reply.

Yeah, I agree that there's nothing in mstform that's inherently client-side/browser-only conceptually, that's why I was quite surprised when I got this error.

It seems that the problem is not in mstform's source-code though, but related to the way webpack compiles UMD modules, see: https://github.com/webpack/webpack/issues/6784.

Any specific reasons you defined the output js' `libraryTarget` to be `umd` here: https://github.com/isprojects/mstform/blob/master/webpack.common.js#L22?

**Comment by fullofcaffeine** [comment]
I think the fix is simple, it's listed in the webpack issue I linked above. I'm currently trying to setup the project so I'm able to build and I'll submit a PR if the fix works.

**Comment by fullofcaffeine** [comment]
I managed to fix the SSR issue here: https://github.com/fullofcaffeine/mstform/commit/5b0a8c70a5210a2dc394ecd07628016cdb7a312c. It now works fine when used from nodejs. 

However, I'm now facing another problem: https://github.com/isprojects/mstform/issues/119. Once I figure this out, I'll gladly open a PR for this issue.

**Comment by MaxSvargal** [comment]
Can't use your lib without nodejs support. So sad =(

**Comment by faassen** [comment]
I am happy to review PRs, please do prod me.:blush:
