### ISSUE TITLE
Is uglifyjs-webpack-plugin plugin being used at all?

### ISSUE THREAD

**Issue by fullofcaffeine** [isprojects/mstform#117]
Getting an error when trying to build:

```
Error: Cannot find module 'uglifyjs-webpack-plugin'
```

Seems this is not being used: https://github.com/isprojects/mstform/blob/1dd4ecd7a6ea0d150b1f20658e51759b6eea2a1a/webpack.prod.js#L3

**Comment by faassen** [comment]
It doesn't appear to be. Weird there's a build error though. I think we need to fix the minification.

**Comment by RickLucassen** [comment]
Closing this, we enabled terser plugin since 1.31.0
