### ISSUE TITLE
[question/advice] Construct mstform from swagger/openapi schema definition?

### ISSUE THREAD

**Issue by leonh** [isprojects/mstform#133]
I'm new to mstform and wondering if my goal is achievable or not, hoping to get some advice from an experienced mstform users...

I have an fastApi/swagger api with an openapi.json definition. Also a react app using mobx I'm considering if it is suitable to attempt to generate forms in my react app that work seamlessly with the api. Without resorting to hand coding the type definitions in mobx models and mstform classes?

Wondering if it is advised/possible/madness to try to construct the mstform and mobx models from the openapi.json definition (eg https://swagger.io/docs/specification/components/) ? 
Going this route, are there any pitfalls likely to be encountered ? 
thanks.

**Comment by faassen** [comment]
Thanks for your question!

We haven't designed mstform for this use case specifically. There is
nothing that stops you from generating a mstform Form definition
programmatically. I think it should also be possible to generate a MST type
programmatically, though you might not benefit from typechecks if you use
TS. I believe there is some MST integration for graphql out there that
could help you on your way with that bit as an example.

Both MST models as well as mstform Form instances are in the end just js
objects you can construct.

A final step might be to generate the UI programmatically. Most real world
UIs tend to be so complicated you need more special casing than you gain,
but it should be possible. It could be we need to expose more introspection
UIs for that.

This is also the risk of generating forms: you might need to supplement
swagger in some ways depending on your use cases. One particular aspect for
instance is how the field is controlled: various HTML elements and React
components use different attributes and change events for that. It may be
that the defaults built into the converter aren't righ

If you try this I would love to hear your feedback!

**Comment by leonh** [comment]
Thanks for the quick reply!
If there are any parts of the mstform api that you think, I should investigate please let me know.

btw. Belated thanks for your work on zope2 & formulator all those years ago. I found it very helpful on a number of projects I was working on at the time.  :-)

**Comment by RickLucassen** [comment]
Closing this due to the age of this issue, if you have any more questions please let us know!
