### ISSUE TITLE
change hook for fields

### ISSUE THREAD

**Issue by faassen** [isprojects/mstform#3]
Sometimes when you modify a field you want another field to be modified along with it. We could implement this with a change hook on the field options.

```javascript
new Field(someConverter, { change: (node, value) => { node.someOtherChange() })
```

the change hook doesn't override the behavior of the normal handleChange -- this still happens. But it lets you take additional actions.

**Comment by Bonemind** [comment]
Feels like a natural an flexible way to do it to me :+1:
