### ISSUE TITLE
Update "mobx-state-tree" peer dependency

### ISSUE THREAD

**Issue by hactrz** [isprojects/mstform#36]
error "mstform#mobx-state-tree@^2.0.5" doesn't satisfy found match of "mobx-state-tree@3.5.0"

**Comment by faassen** [comment]
I'm open to a PR that supports mst 3 as mst 2 in package.json, but for the time being we're still deploying mstform with MST 2.x, so I don't want to break compatibility.

For a bonus we could set up continuous integration that runs the tests with MST 2 and MST 3 and again PRs are welcome.

**Comment by faassen** [comment]
Note: we are currently investigating how much effort it would be to update our mstform-using application to MST 3, in which case we'll retire the MST 2.0 support.
