### ISSUE TITLE
Improve type for value property on accessor

### ISSUE THREAD

**Issue by faassen** [isprojects/mstform#56]
Right now value on a lot of accessors is the 'any' type. This isn't correct, but I spent quite a bit of time to try to derive this information from the underlying model but couldn't make it work.

There are two possible solutions:

* propagate the model type to the underlying accessors again. I removed this when I was cleaning up the types recently, but it might do the trick.

* a bigger change: make it so that any sub form (or repeating indexed form) is really a Form, and define these forms separately with the model type included. Then use the underlying Form object to get the type. The bigger change has potential other benefits: it allows reuse of sub-forms. But it would break compatibility as well.

**Comment by RickLucassen** [comment]
Currently the value type is derived from the generic typing, I think for now that is good enough.

The second point would indeed be a bigger change, so for now this is fine.
