### ISSUE TITLE
MobX 5 support

### ISSUE THREAD

**Issue by Amareis** [isprojects/mstform#63]
We use mobx 5, mstform works well, but there is warning about peer dependecy version. 
![image](https://user-images.githubusercontent.com/4806617/49732236-be72e300-fc9f-11e8-9332-d95feb846cae.png)

**Comment by faassen** [comment]
We ourselves use mobx 4 and it's tested with that. I don't think it would break with mobx 5 however, but we don't do any tests.

We have a few options. I'm open to a PR that also mentions mobx 5 in the peer dependency. On the other hand, we don't actually test this. Nicest would be some continuous integration support that ran this with both mobx 4 and mobx 5.

**Comment by Amareis** [comment]
There is no CI currently? Maybe add travis.org, it's pretty simple to setup and it support build matrix, which can handle different dependency versions too, I think.
https://dyrynda.com.au/blog/testing-multiple-dependency-versions-with-travis-ci

**Comment by kdleijer** [comment]
I have activated travis on our repositories.
`Travis CI
  My Repositories
    Running (0/0)
      isprojects/mstform
      Duration: - `

**Comment by RickLucassen** [comment]
Closing this issue, we are currently supporting MobX 6.
