### ISSUE TITLE
Support enforceActions: 'always'

### ISSUE THREAD

**Issue by ssured** [isprojects/mstform#76]
Thanks for this library

This works
```javascript
import { configure } from 'mobx';
configure({ enforceActions: 'observe' });
```

This doesn't:
```javascript
import { configure } from 'mobx';
configure({ enforceActions: 'always' });
```

The following code from the demo https://github.com/isprojects/mstform/blob/f4be8277f0d9bf6ae3a67453e9f155011238f255/demo/component.tsx#L88 breaks with error: `"Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: t@30.saveStatus"`

I had to ease strictness because of this library, it would be nice if there was support for strict mobx as well.

**Comment by faassen** [comment]
Thank you!

It would indeed be nice to support more strictness. I tried this a long time ago but ran into issues I couldn't figure out -- if I recall correctly there were issues in constructors.
Much has changed in mstform internals in the mean time. I would be open to a PR that implements this but cannot put in the time myself.
