### ISSUE TITLE
Maintaining errors by path can become out of sync in case of repeating form

### ISSUE THREAD

**Issue by faassen** [isprojects/mstform#94]
When we return errors by path with the save function, and we do this for a repeating form, and the user removes or inserts an entry in a repeating form, the paths can become out of sync. They will only be fixed until we save again.

This should not be an issue when we have a process function configured - the backend validation will send new paths with new error information when the user makes changes, so things don't become out of sync.

Still, it would be a better design to store external errors directly on the accessors as soon as information comes in from the backend, instead of working with the `getError` and `getWarning` hook and look things up by paths.

Every accessor should have an internalError, externalError, externalWarning. You can validate while ignoring external errors.

**Comment by RubenvandeKerkhof-isp** [comment]
This feature has been implemented already in earlier releases.
